<img src="https://sv1.picz.in.th/images/2023/05/26/FojNB1.png" alt="FojNB1.png" border="0" />

![FojV51.png](https://sv1.picz.in.th/images/2023/05/26/FojV51.png)

## Use numpy array`()`

In [2]:
import numpy as np
x = np.array(range(1,13))
print(x)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


- **ndarray.reshape`()`**

In [3]:
rx = x.reshape(3,4)
print (x)
print(rx)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


- **view** vs **copy**

In [4]:
x[0] = 100

print(x)
print(rx)

[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [6]:
rx.base

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [7]:
rx = x.reshape(3,4).copy()

x[0] = 500
print(x)
print(rx)

[500   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


- **Row-major** vs **Column-major Order**

In [8]:
# order = 'C' -> row-major order

x = np.array(range(1,13)).reshape(3,4, order='C')
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
# order = 'F' -> column-major order
X = np.array(range(1,13)).reshape(3,4, order='F')
print (x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


- Create **2d array** using numpy.array`()`

In [12]:
x = np.array([[1,2,3], [4,5,6]])

print(x)
print(x. shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Working with Axis

In [14]:
np.sum(x, axis=0)

array([5, 7, 9])

In [15]:
print(x, '\n')
print('np.sum(x, axis=0) =', np.sum(x, axis=0))
print('np.sum(x, axis=1) =', np.sum(x, axis=1))

[[1 2 3]
 [4 5 6]] 

np.sum(x, axis=0) = [5 7 9]
np.sum(x, axis=1) = [ 6 15]


- Create **3d array** using numpy.array`()`

In [19]:
x = np.array([ [ [1,2,3], [4,5,6] ], [ [7,8,9], [10,11,12]]])
print(x)
print(x.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


- Create **ndarray of objects**

In [21]:
x = np.array([ [1,2,3], [4,5,6], [7,8] ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [25]:
x = np.array([ [1,2,3], [4,5,6], [7,8] ], dtype=object)
print(x)
print(x.shape)
print([0],type(x[0]))

[list([1, 2, 3]) list([4, 5, 6]) list([7, 8])]
(3,)
[0] <class 'list'>


## Use numpy.arange`()`
- Create an array using `arange()` based on the specified number range and step.

In [26]:
x = np.arange(10, 90, 10, np.float64)
print (x)
print(x. shape)

[10. 20. 30. 40. 50. 60. 70. 80.]
(8,)


## Use numpy.empty(), numpy.zeros(), numpy.ones()

		numpy.empty(shape, dtype = float, order = 'C')
    
- Create an uninitialized array (i.e. created with whatever values in the allocated memory of ndarray)


In [27]:
m = np.empty((3,2), dtype=int)
print(m)

[[-1806859072         615]
 [-1806859136         615]
 [-1806945856         615]]


In [28]:
m = np.zeros((3,2), dtype=int)
print (m)

[[0 0]
 [0 0]
 [0 0]]


In [30]:
m = np.ones((3,2), dtype=int)
print(m)

[[1 1]
 [1 1]
 [1 1]]
