## Understand array indexing

In [2]:
import numpy as np
x = np.arange(0,12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

- Access **a specific item**

In [4]:
x[0,2] = -9
print(x)

[[ 0  1 -9]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


- Access **an entire row**

In [7]:
x[1] = 8
print(x)

[[ 0  1 -9]
 [ 8  8  8]
 [ 6  7  8]
 [ 9 10 11]]


- Access **an entire column**

In [8]:
x[:,0:2]

array([[ 0,  1],
       [ 8,  8],
       [ 6,  7],
       [ 9, 10]])

## Understand array slicing

- ***Note***: The sliced array is **a VIEW of the original array.**

### Slicing with` [SEEES2TEETET]`

- Similar to the way of indexing list works
- *Notice* that *difference between slicing and direct indexing on specific item*

In [19]:
x = np.arange(0,20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
x[0:4:2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [23]:
x[-3:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
x[:-3]

array([[0, 1, 2, 3, 4]])

### Slicing 3d array

In [25]:
x = np.arange(0,12).reshape(2,3,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [26]:
x[0,0:2,]

array([[0, 1],
       [2, 3]])

### Advanced Indexing

- Use **Integer Indexing** to select arbitrary items in each dimensions

In [27]:
x = np.arange(0,20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
x[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
x[[0,1],[1,3]]#row 0,1 / column 1,3 

array([1, 8])

In [32]:
x[[[1,2],[3,3]] , [[1,2],[1,2]] ]

array([[ 6, 12],
       [16, 17]])

In [35]:
x [[[1,1],[3,3],[0,2]] , [[1,2],[1,2],[2,3]] ]

array([[ 6,  7],
       [16, 17],
       [ 2, 13]])

- Use **Boolean Indexing** to select arbitrary items in each dimensions


- Use **Boolean as Masking index** to select specific elements based on certain criteria.