## Reshape Array


### `reshape() `vs `resize()`
- Change dimension of the existing array


In [1]:
import numpy as np


In [3]:
x = np.arange(1,13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
reshape_x = x.reshape(6,2)
print(reshape_x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [5]:
reshape_x[0,0] = 11
print(reshape_x)
print(x)

[[11  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[11  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
reshape_x.base

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
reshape_x.base is x

True

 **Different from using `resize()`**

- `numpy.resize()` returns the new resized ndarray (not view).


In [12]:
resize_x = np.resize(x, (6,2))
print(resize_x)

[[11  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [14]:
resize_x.base is x

False

In [15]:
resize_x.base

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
print (reshape_x.base is x)
print(resize_x.base is x)

True
False


### `flatten()`

- Convert n-dimension array to 1-d array


In [17]:
resize_x.flatten()

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

###  `transpose()`

- Reverse the axes of array

In [18]:
reshape_x

array([[11,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [20]:
reshape_x.transpose()

array([[11,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [21]:
reshape_x.T

array([[11,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

## Join Array

### `concatenate()`
- Concatenate **array elements along their corresponding, existing axis.**


In [22]:
x = np.arange(0,6).reshape(2,3)
print('x:\n', x, '\n')
y = np.arange(6,12).reshape(2,3)
print('y:\n', y, '\n')

con_ax0 = np.concatenate((x,y))
print('concatenate with axis = 0', '\n')
print(con_ax0, '\n')

con_ax1 = np.concatenate((x,y), axis=1)
print('concatenate with axis = 1', '\n')
print(con_ax1, '\n')

x:
 [[0 1 2]
 [3 4 5]] 

y:
 [[ 6  7  8]
 [ 9 10 11]] 

concatenate with axis = 0 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

concatenate with axis = 1 

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]] 



### `stack()`
- Stack (not concatenate) arrays **on the specified new axis.**

In [23]:
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

x:
 [[0 1 2]
 [3 4 5]] 

x.shape = (2, 3) 

y:
 [[ 6  7  8]
 [ 9 10 11]] 

y.shape = (2, 3) 



In [27]:
st_ax0 = np.stack((x,y))

print('stack with axis = 0\n')
print(st_ax0)
print('\nst_ax0.shape =', st_ax0.shape, '\n')

st_ax1 = np.stack((x,y), axis=1)
print('stack with axis = 1\n')
print(st_ax1)
print('\nst_axl.shape =', st_ax1.shape, '\n')

stack with axis = 0

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

st_ax0.shape = (2, 2, 3) 

stack with axis = 1

[[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]]

st_axl.shape = (2, 2, 3) 



### Add/remove Array Elements

### **`insert()`**

- Insert elements at the specified index.

In [28]:
x = np.arange(0,12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
np.insert(x, 3, 88)

array([ 0,  1,  2, 88,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- Insert **without the specified axis --- array will be flatten.**

In [30]:
rx = x.reshape(4,3)
rx

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.insert(rx, 1, 88)

array([ 0, 88,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
np.insert(rx, 1, 88, axis=0)

array([[ 0,  1,  2],
       [88, 88, 88],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
np.insert(rx, 1, 88, axis=1)

array([[ 0, 88,  1,  2],
       [ 3, 88,  4,  5],
       [ 6, 88,  7,  8],
       [ 9, 88, 10, 11]])

### **`delete()`**

- Delete elements at the spelified index and axis.
- Similar to *`insert()`*, the array will be flatted before performing delete if axis is not specified.

In [34]:
X = np.arange(0,12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
np.delete(x,1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
rx = x.reshape(4,3)
rx

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
np.delete(rx, 1, axis=0)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
np.delete(rx, 1, axis=1)

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [41]:
np.delete(rx, 1) ## !!!

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])