<img src="https://sv1.picz.in.th/images/2023/05/26/FDm19I.png" alt="FDmMft.png" width=900    hight=500 >

<img src="https://sv1.picz.in.th/images/2023/05/26/FDmMft.png" alt="FDmMft.png" width=900    hight=500 >

## NumPy - Basic Operations

In [3]:
import numpy as np

### Vectorization and Broadcasting

#### NumPy operations on arrays with the same shape

In [4]:
#Vectorization
x = np.arange(0,5)
print('x:\n', x, '\n')

y = np.arange(5,10)
print('y:\n', y, '\n')

print (x+y)

x:
 [0 1 2 3 4] 

y:
 [5 6 7 8 9] 

[ 5  7  9 11 13]


In [9]:
x = np.arange(0,5)
print('x:\n', x, '\n')
print('x.shape =', x.shape)

y = np.arange(5,6)
print('y:\n', y, '\n')
print('y.shape =', y.shape)

x:
 [0 1 2 3 4] 

x.shape = (5,)
y:
 [5] 

y.shape = (1,)


In [10]:
x+y

array([5, 6, 7, 8, 9])

## NumPy operations on arrays with compatible dimensions



- with **1-d arrays**

In [11]:
x = np.arange(0,5)
print('x:\n', x, '\n')
print('x.shape =', x.shape)

y = np.array([10])
print('y:\n', y, '\n')
print('y.shape =', y.shape)

print('x*y:\n', x*y)

x:
 [0 1 2 3 4] 

x.shape = (5,)
y:
 [10] 

y.shape = (1,)
x*y:
 [ 0 10 20 30 40]


- with **2-d arrays**

In [16]:
x = np.arange(0,12).reshape(2,6)
print('x:\n', x, '\n')
print('x.shape =', x.shape)

y = np.arange(0,6).reshape(1,6)
print('y:\n', y, '\n')
print('y.shape =', y.shape)
print('x*y:\n', x*y)

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

x.shape = (2, 6)
y:
 [[0 1 2 3 4 5]] 

y.shape = (1, 6)
x*y:
 [[ 0  1  4  9 16 25]
 [ 0  7 16 27 40 55]]


- with **3-d arrays**

In [17]:
x = np.arange(0,18).reshape(2,3,3)
print('x:\n', x, '\n')
print('x.shape =', x.shape)

y = np.arange(0,6).reshape(2,3,1)
print('y:\n', y, '\n')
print('y.shape =', y.shape)
print('x*y:\n', x*y)

x:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 

x.shape = (2, 3, 3)
y:
 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] 

y.shape = (2, 3, 1)
x*y:
 [[[ 0  0  0]
  [ 3  4  5]
  [12 14 16]]

 [[27 30 33]
  [48 52 56]
  [75 80 85]]]


- two arrays with **different number of dimensions**


In [18]:
x = np.arange(0,6).reshape(2,3)
print('x:\n', x, '\n')
print('x.shape =', x.shape)

y = np.arange(0,3)
print('y:\n', y, '\n')
print('y.shape =', y.shape)
print('x*y:\n', x*y)

x:
 [[0 1 2]
 [3 4 5]] 

x.shape = (2, 3)
y:
 [0 1 2] 

y.shape = (3,)
x*y:
 [[ 0  1  4]
 [ 0  4 10]]
