<img src="https://sv1.picz.in.th/images/2023/05/26/FA0vO9.png" width = 800   />

## A Look at Math Operations

In [9]:
import numpy as np
scores = np.array([
    [75,80,85],
	[85,80,75],
	[80,85,90],
	[90,85,80],
	[70,80,90]
])
    
print(scores)

[[75 80 85]
 [85 80 75]
 [80 85 90]
 [90 85 80]
 [70 80 90]]


In [12]:
print(np.min(scores, axis=0))
print('\n')
print(np.min(scores, axis=1))

[70 80 75]


[75 75 80 80 70]


In [13]:
print(np.max(scores, axis=0))
print('\n')
print(np.max(scores, axis=1))

[90 85 90]


[85 85 90 90 90]


In [14]:
print(np.mean(scores, axis=0))
print('\n')
print(np.mean(scores, axis=1))

[80. 82. 84.]


[80. 80. 85. 85. 80.]


In [15]:
print(np.sum(scores, axis=1))

[240 240 255 255 240]


In [19]:
x = np.arange(-5,5)
print('x:', x)

y = 2*x +10

print('y:', y)

x: [-5 -4 -3 -2 -1  0  1  2  3  4]
y: [ 0  2  4  6  8 10 12 14 16 18]


## Sorting and Filtering/Searching

- Use `numpy.sort()` --> return a **copy** of sorted ndarray.

In [20]:
scores

array([[75, 80, 85],
       [85, 80, 75],
       [80, 85, 90],
       [90, 85, 80],
       [70, 80, 90]])

In [21]:
#ascending sort
print(np.sort(scores, axis=0))
print('\n')
print(np.sort(scores, axis=1))

[[70 80 75]
 [75 80 80]
 [80 80 85]
 [85 85 90]
 [90 85 90]]


[[75 80 85]
 [75 80 85]
 [80 85 90]
 [80 85 90]
 [70 80 90]]


In [22]:
print(-(np.sort(-scores, axis=1)))

[[85 80 75]
 [85 80 75]
 [90 85 80]
 [90 85 80]
 [90 80 70]]


- Sort by **structure field** - order by `field_name`

In [23]:
# create customer data type
customer_dtype = np.dtype([('cid', str, 10), ('name', str, 30), ('age', np.int8)])

# create customer records
cust_list = [('C100', 'David', 35), ('C200', 'Steve', 25), ('C300', 'Tom',45)]

# create NumPy array
customers = np.array(cust_list, customer_dtype)

print(customers)


[('C100', 'David', 35) ('C200', 'Steve', 25) ('C300', 'Tom', 45)]


In [24]:
print(np.sort(customers, order='age'))

[('C200', 'Steve', 25) ('C100', 'David', 35) ('C300', 'Tom', 45)]


In [25]:
print (np.sort(customers, order='age')[::-1])

[('C300', 'Tom', 45) ('C100', 'David', 35) ('C200', 'Steve', 25)]
