<a href="https://www.picz.in.th/image/FANvO8"><img src="https://sv1.picz.in.th/images/2023/05/26/FANvO8.png" alt="population vs sample" border="0"  width=850 hight=500/></a>

<img src="https://sv1.picz.in.th/images/2023/05/26/FAB03l.png" alt="population vs sample2" border="0" width=850 hight=500 />

<img src="https://sv1.picz.in.th/images/2023/05/26/FABfdQ.png" alt="population vs sample3" border="0" width=850 hight=500/>

## NumPy - Random Sampling

In [1]:
import numpy as np
from numpy.random import default_rng

# Random Number Generator

## Recent NumPy Versions

- The new approach to generate random numbers in NumPy with better statistical properties.


In [2]:
# Create object of default random number generator
rng = default_rng()
# Random 5 float numbers from 0.0 to 1.0
rng.random(5)

array([0.35741431, 0.26172963, 0.05443541, 0.38580493, 0.09816704])

## Legacy Versions

In [3]:
#Old version
from numpy import random

random. rand(5) 

array([0.98676214, 0.92159554, 0.8871501 , 0.52948658, 0.02536325])

## Seed Number

- Use to **control the sequence of random state of random number generator**


In [6]:
# seed = 2021
rng = default_rng(2021)

rng.random(50)

array([0.75694783, 0.94138187, 0.59246304, 0.31884171, 0.62607384,
       0.03551387, 0.25212696, 0.48501366, 0.30126688, 0.72195094,
       0.92989066, 0.90823581, 0.08495856, 0.27036617, 0.97168176,
       0.26015007, 0.80052031, 0.79827865, 0.6425692 , 0.66806864,
       0.23521315, 0.02190576, 0.12961145, 0.12298406, 0.45408739,
       0.47734517, 0.66692504, 0.80072716, 0.42069822, 0.11445225,
       0.25617877, 0.48995179, 0.08528271, 0.7167631 , 0.33100379,
       0.61018338, 0.59819869, 0.82549985, 0.88627002, 0.85022632,
       0.52795471, 0.46057818, 0.02466648, 0.93499413, 0.33640568,
       0.13258264, 0.19667242, 0.3612112 , 0.23337686, 0.15231137])

In [7]:
# seed = 2021
rng = default_rng(2021)

rng.random(50)

array([0.75694783, 0.94138187, 0.59246304, 0.31884171, 0.62607384,
       0.03551387, 0.25212696, 0.48501366, 0.30126688, 0.72195094,
       0.92989066, 0.90823581, 0.08495856, 0.27036617, 0.97168176,
       0.26015007, 0.80052031, 0.79827865, 0.6425692 , 0.66806864,
       0.23521315, 0.02190576, 0.12961145, 0.12298406, 0.45408739,
       0.47734517, 0.66692504, 0.80072716, 0.42069822, 0.11445225,
       0.25617877, 0.48995179, 0.08528271, 0.7167631 , 0.33100379,
       0.61018338, 0.59819869, 0.82549985, 0.88627002, 0.85022632,
       0.52795471, 0.46057818, 0.02466648, 0.93499413, 0.33640568,
       0.13258264, 0.19667242, 0.3612112 , 0.23337686, 0.15231137])