## Basic Random Numbers

![basic random](https://techvidvan.com/tutorials/wp-content/uploads/sites/2/2020/07/Built-in-functions-for-generating-random-numbers-in-python-Copy.jpg)  

### Random Integer

In [4]:
import numpy as np
from numpy.random import default_rng
rng = default_rng()

rng.integers(low=0, high=10, endpoint=True, size=5)

array([ 1, 10,  6,  2, 10], dtype=int64)

### Random Float Numbers

- Random float numbers from [ 0.0, 1.0 ]

In [5]:
rng.random(5)

array([0.93380562, 0.68614467, 0.89215885, 0.15149048, 0.12410956])

In [6]:
rng. random(10).reshape(2,5)

array([[0.8528616 , 0.41256962, 0.11040869, 0.37702464, 0.92822548],
       [0.88648792, 0.3209996 , 0.916406  , 0.54638705, 0.58786919]])

## Random a sample from a given dataset


- Random from **1d array dataset**

In [7]:
int_ds = np.arange(0,150,3)
int_ds

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147])

In [8]:
rng.choice(int_ds, size=10)

array([117,  90,  78,   3, 138, 108,  66, 132,  42,  90])

In [9]:
rng.choice(int_ds, size=(5,2))

array([[147, 123],
       [135,  51],
       [ 21, 141],
       [ 69, 132],
       [ 21,  18]])

- Random from **2d array dataset**

In [10]:
int_ds2 = int_ds.reshape(5,10)
int_ds2

array([[  0,   3,   6,   9,  12,  15,  18,  21,  24,  27],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 60,  63,  66,  69,  72,  75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102, 105, 108, 111, 114, 117],
       [120, 123, 126, 129, 132, 135, 138, 141, 144, 147]])

- Random along **axis=0 (row), but select all columns of the sampled rows**

In [11]:
x = rng.choice(int_ds2, size=(2,), axis=0)
print(x, '\n')
print('x.shape:', x.shape)

[[ 90  93  96  99 102 105 108 111 114 117]
 [ 30  33  36  39  42  45  48  51  54  57]] 

x.shape: (2, 10)


- Random along **axis=1 (column), but select all rows of the sampled columns **

In [13]:
x = rng.choice(int_ds2, size=(2,), axis=1)
print(x, '\n')
print('x.shape:', x.shape)

[[ 27  24]
 [ 57  54]
 [ 87  84]
 [117 114]
 [147 144]] 

x.shape: (5, 2)


## Permutation

### shuffle method

- **Shuffle** the array and update it **in-place** with the shuffled values.

In [18]:
x = np.arange(0,10)
print(x)
print('\n')

rng = default_rng()
rng. shuffle(x)
print (x)

[0 1 2 3 4 5 6 7 8 9]


[1 8 5 3 9 7 6 2 4 0]


In [21]:
x = np.arange(0,12).reshape(3,4)
print(x, '\n')

rng.shuffle(x, axis=0)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [22]:
x = np.arange(0,12).reshape(3,4)
print(x, '\n')

rng.shuffle(x, axis=1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  2  3  1]
 [ 4  6  7  5]
 [ 8 10 11  9]]


### permuted method

Use **permuted()** method - create a **new shuffled array**

In [23]:
x = np.arange(0,10)
print(x, '\n')

pm = rng.permuted(x)
print (pm)

[0 1 2 3 4 5 6 7 8 9] 

[0 3 7 9 5 2 4 6 1 8]


In [24]:
x is pm

False